version: '3.9'

services:
  fastapi:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: fastapi_app
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose:
      - 8000
    networks:
      - backend

  db:
    image: postgres:14-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    restart: always
    networks:
      - backend

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    depends_on:
      - fastapi
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
